package com.quzzar.vestige.travel;

import net.minecraft.util.StringRepresentable;

/** Generated by tools/author_standing_stones.py. Cosmetic forms never change network identity. */
public enum StandingStoneShape implements StringRepresentable {
    BLADE("blade", 7, 23.52, 6),
    SHOULDER("shoulder", 8, 23.52, 4),
    LEANING("leaning", 10, 23.52, 5),
    SPIRE("spire", 7.5, 23, 6),
    WEDGE("wedge", 6, 20, 4),
    CROWN("crown", 8, 24, 5),
    FANG("fang", 8.7, 19, 5),
    CLEFT("cleft", 8, 24, 4),
    HUNCHED("hunched", 7.5, 21, 3),
    TAPER("taper", 7, 23, 5),
    SLANT("slant", 7.5, 24, 4),
    TABLET("tablet", 8, 22, 6),
    CHISEL("chisel", 7.5, 24, 7),
    SADDLE("saddle", 7.5, 19, 4),
    OBELISK("obelisk", 8, 23.5, 5),
    KEEL("keel", 8, 23, 6);
    private final String id;
    private final double runeX, runeY, runeZ;
    StandingStoneShape(String id, double runeX, double runeY, double runeZ) {
        this.id = id; this.runeX = runeX / 16; this.runeY = runeY / 16; this.runeZ = runeZ / 16;
    }
    @Override public String getSerializedName() { return id; }
    public double runeX() { return runeX; }
    public double runeY() { return runeY; }
    public double runeZ() { return runeZ; }
    public static StandingStoneShape fromKey(String key) {
        if (!StoneNetwork.validKey(key)) return BLADE;
        // Fixed sixteen-way policy; adding another enum value must not remap existing keys.
        return switch (Integer.parseInt(key.substring(62), 16) & 15) {
            case 0 -> BLADE;
            case 1 -> LEANING;
            case 2 -> SPIRE;
            case 3 -> WEDGE;
            case 4 -> SHOULDER;
            case 5 -> CROWN;
            case 6 -> FANG;
            case 7 -> CLEFT;
            case 8 -> HUNCHED;
            case 9 -> TAPER;
            case 10 -> SLANT;
            case 11 -> TABLET;
            case 12 -> CHISEL;
            case 13 -> SADDLE;
            case 14 -> OBELISK;
            case 15 -> KEEL;
            default -> throw new IllegalStateException("Four-bit signature bucket required");
        };
    }
}
