package com.quzzar.vestige.apparatus;

import net.minecraft.resources.ResourceLocation;

/** Generated by tools/author_apparatus_models.py. Cosmetic carriers have identical behavior. */
public enum ApparatusMaterials {
    STONE("stone", "minecraft:stone", "minecraft:stone_slab"),
    COBBLESTONE("cobblestone", "minecraft:cobblestone", "minecraft:cobblestone_slab"),
    MOSSY_COBBLESTONE("mossy_cobblestone", "minecraft:mossy_cobblestone", "minecraft:mossy_cobblestone_slab"),
    STONE_BRICKS("stone_bricks", "minecraft:stone_bricks", "minecraft:stone_brick_slab"),
    MOSSY_STONE_BRICKS("mossy_stone_bricks", "minecraft:mossy_stone_bricks", "minecraft:mossy_stone_brick_slab"),
    GRANITE("granite", "minecraft:granite", "minecraft:granite_slab"),
    POLISHED_GRANITE("polished_granite", "minecraft:polished_granite", "minecraft:polished_granite_slab"),
    DIORITE("diorite", "minecraft:diorite", "minecraft:diorite_slab"),
    POLISHED_DIORITE("polished_diorite", "minecraft:polished_diorite", "minecraft:polished_diorite_slab"),
    ANDESITE("andesite", "minecraft:andesite", "minecraft:andesite_slab"),
    POLISHED_ANDESITE("polished_andesite", "minecraft:polished_andesite", "minecraft:polished_andesite_slab"),
    SANDSTONE("sandstone", "minecraft:sandstone", "minecraft:sandstone_slab"),
    SMOOTH_SANDSTONE("smooth_sandstone", "minecraft:smooth_sandstone", "minecraft:smooth_sandstone_slab"),
    RED_SANDSTONE("red_sandstone", "minecraft:red_sandstone", "minecraft:red_sandstone_slab"),
    SMOOTH_RED_SANDSTONE("smooth_red_sandstone", "minecraft:smooth_red_sandstone", "minecraft:smooth_red_sandstone_slab"),
    BRICKS("bricks", "minecraft:bricks", "minecraft:brick_slab"),
    MUD_BRICKS("mud_bricks", "minecraft:mud_bricks", "minecraft:mud_brick_slab"),
    QUARTZ("quartz", "minecraft:quartz_block", "minecraft:quartz_slab"),
    SMOOTH_QUARTZ("smooth_quartz", "minecraft:smooth_quartz", "minecraft:smooth_quartz_slab"),
    PRISMARINE("prismarine", "minecraft:prismarine", "minecraft:prismarine_slab"),
    PRISMARINE_BRICKS("prismarine_bricks", "minecraft:prismarine_bricks", "minecraft:prismarine_brick_slab"),
    DARK_PRISMARINE("dark_prismarine", "minecraft:dark_prismarine", "minecraft:dark_prismarine_slab"),
    NETHER_BRICKS("nether_bricks", "minecraft:nether_bricks", "minecraft:nether_brick_slab"),
    RED_NETHER_BRICKS("red_nether_bricks", "minecraft:red_nether_bricks", "minecraft:red_nether_brick_slab"),
    BLACKSTONE("blackstone", "minecraft:blackstone", "minecraft:blackstone_slab"),
    POLISHED_BLACKSTONE("polished_blackstone", "minecraft:polished_blackstone", "minecraft:polished_blackstone_slab"),
    POLISHED_BLACKSTONE_BRICKS("polished_blackstone_bricks", "minecraft:polished_blackstone_bricks", "minecraft:polished_blackstone_brick_slab"),
    COBBLED_DEEPSLATE("cobbled_deepslate", "minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate_slab"),
    POLISHED_DEEPSLATE("polished_deepslate", "minecraft:polished_deepslate", "minecraft:polished_deepslate_slab"),
    DEEPSLATE_BRICKS("deepslate_bricks", "minecraft:deepslate_bricks", "minecraft:deepslate_brick_slab"),
    DEEPSLATE_TILES("deepslate_tiles", "minecraft:deepslate_tiles", "minecraft:deepslate_tile_slab"),
    TUFF("tuff", "minecraft:tuff", "minecraft:tuff_slab"),
    POLISHED_TUFF("polished_tuff", "minecraft:polished_tuff", "minecraft:polished_tuff_slab"),
    TUFF_BRICKS("tuff_bricks", "minecraft:tuff_bricks", "minecraft:tuff_brick_slab"),
    END_STONE_BRICKS("end_stone_bricks", "minecraft:end_stone_bricks", "minecraft:end_stone_brick_slab"),
    PURPUR("purpur", "minecraft:purpur_block", "minecraft:purpur_slab");

    private final String id;
    private final ResourceLocation body;
    private final ResourceLocation slab;
    ApparatusMaterials(String id, String body, String slab) {
        this.id = id;
        this.body = ResourceLocation.parse(body);
        this.slab = ResourceLocation.parse(slab);
    }
    public String id() { return id; }
    public ResourceLocation body() { return body; }
    public ResourceLocation slab() { return slab; }
    public String blockName(ApparatusBlock.Role role) {
        return this == STONE_BRICKS ? role.path() : id + "_" + role.path();
    }
}
