#!/usr/bin/env python3
"""Report native staff affinity pools from source spell traits, without changing content."""
import argparse
import json
import math
from pathlib import Path

from spell_title import spell_title

ROOT = Path(__file__).resolve().parents[1]
SPELLS = ROOT / 'src/main/resources/data/vestige/runtime_spells'
REPORT = ROOT / 'docs/staff-trait-coverage.json'
GUIDE = ROOT / 'docs/staff-trait-coverage.md'
EXCLUDED = {'vestige:amplify', 'vestige:range', 'vestige:area'}


def outputs():
    pools = {}
    spells = []
    for path in sorted(SPELLS.glob('*.json')):
        data = json.loads(path.read_text())
        identity = 'vestige:' + path.stem
        name = data.get('source', {}).get('name', spell_title(path.stem.replace('_', ' ')))
        spells.append(identity)
        for trait, rating in sorted(data['traits'].items()):
            if isinstance(rating, bool) or not isinstance(rating, (float, int)) or not math.isfinite(rating) or rating < 0:
                raise ValueError(f'{identity}: invalid {trait} rating')
            if rating > 0:
                pools.setdefault(trait, []).append({'spell': identity, 'name': name})
    catalog = {
        'scope': 'Checked-in native base traits only; equipment and shaping cannot qualify a missing affinity.',
        'spell_count': len(spells),
        'excluded_affinities': sorted(EXCLUDED),
        'traits': {trait: {'allowed_affinity': trait not in EXCLUDED, 'count': len(entries), 'spells': entries} for trait, entries in sorted(pools.items())},
    }
    lines = [
        '# Staff trait coverage', '',
        'Generated by `python3 tools/audit_staff_traits.py`; verify with `--check`.', '',
        '**Checked-in affinity audit.** The native staff validates these base traits against the loaded server catalog. Eligibility here requires a positive base spell rating in the staff’s fixed trait. Additional spell traits are allowed. Rating magnitude and rarity do not change eligibility. Each base spell is listed once; stored scroll variants keep their own shaping. The owner excludes Amplify, Range and Area as staff affinities; those three rows remain visible as audit evidence.', '',
        f'The checked-in catalog contains **{len(spells)} spells** with **{len(pools)} represented traits**. The JSON companion contains every matching spell ID and source display name. Datapacks can change these pools; native staff binding must validate against the successfully loaded server catalog.', '',
        '| Trait | Allowed affinity | Matching base spells | Catalog coverage |',
        '| --- | --- | ---: | ---: |',
    ]
    for trait, entries in sorted(pools.items()):
        lines.append(f'| `{trait}` | {"No" if trait in EXCLUDED else "Yes"} | {len(entries)} | {len(entries) / len(spells):.1%} |')
    lines += [
        '', '## Balance implication', '',
        'The owner excludes the three scaling traits from affinity selection. Other traits remain open and namespaced, including school and element traits. This exclusion does not remove scaling traits from the stored spells or their effect calculations. Broad schools can still make a staff a wide collection; no acquisition rank or numerical trait bonus is introduced.', '',
        'More slots increase choice, not potency. A spell with Fire 1 and one with Fire 4 both qualify for Fire; the staff does not amplify one more than the other. A Fire spell need not be exclusively Fire. A staff component cannot add Fire to an unrelated spell to qualify it.', '',
        'See [staff design](design/staff-crafting.md) for accepted directions, proposals and implementation boundaries.', '',
    ]
    return {REPORT: json.dumps(catalog, indent=2, ensure_ascii=False) + '\n', GUIDE: '\n'.join(lines)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit('Staff trait coverage is stale: ' + ', '.join(stale))
    print('Staff trait coverage checked.' if args.check else 'Staff trait coverage generated.')


if __name__ == '__main__':
    main()
