#!/usr/bin/env python3
"""Generate native faceted monoliths and all 36 shared masonry finishes."""
import argparse
import json
from pathlib import Path
from standing_stone_geometry import PROFILES, SIGNATURE_BUCKETS, obj, slices

ROOT = Path(__file__).resolve().parents[1]
RESOURCES = ROOT / 'src/main/resources'
PALETTE = ROOT / 'docs/design/apparatus-materials.json'


def block_name(material):
    return 'standing_stone' if material['id'] == 'stone_bricks' else material['id'] + '_standing_stone'


def model(profile, part, texture):
    return {'loader': 'neoforge:obj', 'model': f'vestige:models/block/standing_stone_{profile}_{part}.obj',
            'automatic_culling': False, 'shade_quads': True, 'flip_v': False, 'emissive_ambient': False,
            'ambientocclusion': False, 'textures': {'body': texture, 'particle': texture}}


def collision_source():
    data = []
    for profile in PROFILES.values():
        data.append([slices(profile, half) for half in (0, 1)])
    # Each profile gets its own initializer to stay below Java's method-size limit.
    calls = ', '.join(f'profile{i}Bands()' for i in range(len(data)))
    methods = []
    for i, profile in enumerate(data):
        arrays = ',\n'.join('            {\n' + ',\n'.join('                {' + ', '.join(f'{v:.6f}' for v in box) + '}' for box in half) + '\n            }' for half in profile)
        methods.append(f'    private static double[][][] profile{i}Bands() {{\n        return new double[][][] {{\n' + arrays + '\n        };\n    }\n')
    return '''package com.quzzar.vestige.travel;

import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.properties.DoubleBlockHalf;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

/** Generated by tools/author_standing_stones.py. Quarter-unit bands follow the native silhouettes. */
final class StandingStoneCollision {
    private static final double[][][][] BANDS = {''' + calls + '''};
    private static final VoxelShape[][][] SHAPES = build();
    private StandingStoneCollision() { }
''' + ''.join(methods) + '''
    static VoxelShape shape(StandingStoneShape profile, DoubleBlockHalf half, Direction facing) {
        return SHAPES[profile.ordinal()][half == DoubleBlockHalf.LOWER ? 0 : 1][facing.get2DDataValue()];
    }
    private static VoxelShape[][][] build() {
        var result = new VoxelShape[BANDS.length][2][4];
        for (int p = 0; p < BANDS.length; p++) for (int h = 0; h < 2; h++) for (var facing : Direction.Plane.HORIZONTAL) {
            VoxelShape shape = Shapes.empty();
            for (var b : BANDS[p][h]) {
                VoxelShape part = switch (facing) {
                    case NORTH -> Block.box(b[0], b[1], b[2], b[3], b[4], b[5]);
                    case EAST -> Block.box(16-b[5], b[1], b[0], 16-b[2], b[4], b[3]);
                    case SOUTH -> Block.box(16-b[3], b[1], 16-b[5], 16-b[0], b[4], 16-b[2]);
                    case WEST -> Block.box(b[2], b[1], 16-b[3], b[5], b[4], 16-b[0]);
                    default -> throw new IllegalArgumentException("Horizontal facing required");
                };
                shape = Shapes.or(shape, part);
            }
            result[p][h][facing.get2DDataValue()] = shape.optimize();
        }
        return result;
    }
}
'''


def shape_source():
    """Keep ink anchors, collision indices, inventory predicates and key selection in one ledger."""
    declarations = ',\n'.join(f'    {name.upper()}("{name}", {p["runes"][0]}, {p["runes"][1]}, {p["front"]})'
                             for name, p in PROFILES.items())
    selection = '\n'.join(f'            case {i} -> {name.upper()};' for i, name in enumerate(SIGNATURE_BUCKETS))
    return '''package com.quzzar.vestige.travel;

import net.minecraft.util.StringRepresentable;

/** Generated by tools/author_standing_stones.py. Cosmetic forms never change network identity. */
public enum StandingStoneShape implements StringRepresentable {
''' + declarations + ''';
    private final String id;
    private final double runeX, runeY, runeZ;
    StandingStoneShape(String id, double runeX, double runeY, double runeZ) {
        this.id = id; this.runeX = runeX / 16; this.runeY = runeY / 16; this.runeZ = runeZ / 16;
    }
    @Override public String getSerializedName() { return id; }
    public double runeX() { return runeX; }
    public double runeY() { return runeY; }
    public double runeZ() { return runeZ; }
    public static StandingStoneShape fromKey(String key) {
        if (!StoneNetwork.validKey(key)) return BLADE;
        // Fixed sixteen-way policy; adding another enum value must not remap existing keys.
        return switch (Integer.parseInt(key.substring(62), 16) & 15) {
''' + selection + '''
            default -> throw new IllegalStateException("Four-bit signature bucket required");
        };
    }
}
'''


def generated_files():
    materials = json.loads(PALETTE.read_text())['materials']
    assert len(materials) == 36 and len({m['id'] for m in materials}) == 36
    outputs = {}
    mesh_dir = RESOURCES / 'assets/vestige/models/block'
    for profile, geometry in PROFILES.items():
        for half, part in ((0, 'lower'), (1, 'upper'), (None, 'whole')):
            outputs[mesh_dir / f'standing_stone_{profile}_{part}.obj'] = obj(geometry, half)
    outputs[mesh_dir / 'standing_stones.mtl'] = 'newmtl stone\nKd 1 1 1\nKa 0 0 0\nmap_Kd #body\n'
    outputs[ROOT / 'src/main/java/com/quzzar/vestige/travel/StandingStoneCollision.java'] = collision_source()
    outputs[ROOT / 'src/main/java/com/quzzar/vestige/travel/StandingStoneShape.java'] = shape_source()
    names = []
    lang_path = RESOURCES / 'assets/vestige/lang/en_us.json'
    language = json.loads(lang_path.read_text())
    for material in materials:
        name = block_name(material)
        names.append('vestige:' + name)
        variants = {}
        for profile in PROFILES:
            for part in ('lower', 'upper'):
                path = f'{name}_{profile}_{part}'
                outputs[mesh_dir / (path + '.json')] = model(profile, part, material['textures']['stone'])
                for facing, angle in (('north', 0), ('east', 90), ('south', 180), ('west', 270)):
                    variants[f'facing={facing},half={part},profile={profile}'] = {'model': 'vestige:block/' + path, 'y': angle}
        outputs[RESOURCES / 'assets/vestige/blockstates' / (name + '.json')] = {'variants': variants}
        # Keep the original block model path as a valid lower-part alias for external references.
        outputs[mesh_dir / (name + '.json')] = {'parent': f'vestige:block/{name}_blade_lower'}
        for profile in PROFILES:
            item = model(profile, 'whole', material['textures']['stone'])
            item['display'] = {
                'gui': {'rotation': [30, 225, 0], 'translation': [0, -3, 0], 'scale': [.38, .38, .38]},
                'ground': {'translation': [0, 2, 0], 'scale': [.18, .18, .18]},
                'fixed': {'translation': [0, -4, 0], 'scale': [.45, .45, .45]},
                'thirdperson_righthand': {'rotation': [75, 45, 0], 'translation': [0, 1, 0], 'scale': [.24, .24, .24]},
                'firstperson_righthand': {'rotation': [0, 45, 0], 'translation': [0, -3, 0], 'scale': [.35, .35, .35]}}
            if profile == 'blade':
                item['overrides'] = [{'predicate': {'vestige:stone_shape': i}, 'model': f'vestige:item/{name}_{p}'}
                                     for i, p in enumerate(PROFILES) if i]
            outputs[RESOURCES / 'assets/vestige/models/item' / (name + ('' if profile == 'blade' else '_' + profile) + '.json')] = item
        outputs[RESOURCES / 'data/vestige/loot_table/blocks' / (name + '.json')] = {
            'type': 'minecraft:block', 'pools': [{'rolls': 1, 'entries': [{
                'type': 'minecraft:item', 'name': 'vestige:' + name,
                'functions': [{'function': 'minecraft:copy_components', 'source': 'block_entity',
                               'include': ['minecraft:custom_data', 'minecraft:custom_name']}]}],
                'conditions': [{'condition': 'minecraft:survives_explosion'},
                               {'condition': 'minecraft:block_state_property', 'block': 'vestige:' + name,
                                'properties': {'half': 'lower'}}]}]}
        language['block.vestige.' + name] = material['name'] + ' Standing Stone'
    outputs[lang_path] = language
    outputs[RESOURCES / 'data/vestige/tags/block/standing_stones.json'] = {'replace': False, 'values': names}
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, value in generated_files().items():
        data = value if isinstance(value, str) else json.dumps(value, indent=2) + '\n'
        if args.check:
            assert path.is_file() and path.read_text() == data, 'Standing Stone drift: ' + str(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(data)
    print(f'36 finishes × {len(PROFILES)} native monoliths: ' + ('checked' if args.check else 'generated'))


if __name__ == '__main__':
    main()
