#!/usr/bin/env python3
"""Bundle the equipment review's canonical JSON so local file previews work without fetch."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REVIEW = ROOT / "docs/art/magic-equipment-review"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = {
        "review": json.loads((REVIEW / "review.json").read_text()),
        "abilities": json.loads((REVIEW / "ability-proposals.json").read_text()),
    }
    review_ids = [item["id"] for item in data["review"]["items"]]
    ability_ids = [item["id"] for item in data["abilities"]["items"]]
    if review_ids != ability_ids:
        raise SystemExit("Equipment review and ability proposals disagree")
    output = "// Generated by tools/author_equipment_review.py; edit the source JSON.\n"
    output += "window.VESTIGE_EQUIPMENT_REVIEW = " + json.dumps(data, ensure_ascii=True, separators=(",", ":")) + ";\n"
    path = REVIEW / "review-data.js"
    if args.check:
        if not path.exists() or path.read_text() != output:
            raise SystemExit("Equipment review bundle has drifted; run tools/author_equipment_review.py")
        print("Equipment review bundle agrees with both source files")
    else:
        path.write_text(output)
        print("Bundled six equipment proposals")


if __name__ == "__main__":
    main()
