package com.quzzar.vestige.apparatus.client;

import com.quzzar.vestige.VestigeMainMod;
import com.quzzar.vestige.apparatus.ApparatusBlocks;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;

/** Generated by tools/author_apparatus_models.py; colors only the approved edging. */
@EventBusSubscriber(modid = VestigeMainMod.MOD_ID, bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public final class ApparatusColors {
    public static final int TINT_INDEX = 0;
    public static final int TINT_COLOR = 0xffd9d9d9;

    private ApparatusColors() { }
    private static int color(int tint) { return tint == TINT_INDEX ? TINT_COLOR : -1; }

    @SubscribeEvent public static void blocks(RegisterColorHandlersEvent.Block event) {
        event.register((state, level, pos, tint) -> color(tint), ApparatusBlocks.all().toArray(Block[]::new));
    }

    @SubscribeEvent public static void items(RegisterColorHandlersEvent.Item event) {
        event.register((stack, tint) -> color(tint), ApparatusBlocks.all().stream().map(Block::asItem).toArray(Item[]::new));
    }
}
